apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bbms-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/absakran01/bbms-config.git'
    targetRevision: HEAD
    path: manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true