kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-nfs-pvc
  namespace: prod
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
