apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  org: absakran

namespace: prod

commonAnnotations:
  owner: absakran
  buildTool: kustomize

resources:
- namespaces/
- services/
- storage/
- deployments/
- ingresses/