apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbms-mongodb
  namespace: prod

spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: bbms-mongodb
  template:
    metadata:
      labels:
        app: bbms-mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
        env:
        - name: MONGO_INITDB_DATABASE
          value: "bbms"
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongodb-nfs-pvc