apiVersion: apps/v1
kind: Deployment
metadata:
  name: bbms-fe
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bbms-fe
  template:
    metadata:
      labels:
        app: bbms-fe
    spec:
      containers:
      - image:  absakran01-registry.onrender.com/bbms-fe:latest
        name: bbms-fe
        resources: {}
status: {}
