apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2026-04-20T18:22:00Z"
  name: bbms-mongodb
  namespace: prod
spec:
  # clusterIP: {{CLUSTER_IP}}
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    app: bbms-mongodb
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
